version: 2
jobs:
  build:
    working_directory: ~/ig-images-frontend
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          key: ig-images-frontend-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: ig-images-frontend-{{ checksum "package-lock.json" }}
          paths:
            - node_modules/
      - run:
          name: ESLint
          command: ./node_modules/.bin/eslint .
      - run:
          name: Flow type-checking
          command: ./node_modules/.bin/flow
      - run:
          name: Build
          command: npm run build
      # - run:
      #     name: AVA tests
      #     command: npm run ava
      # - run:
      #     name: Remove tests from dist
      #     command: npm run del -- ./dist/**/*.test.{js,js.map}
      - store_artifacts:
          path: dist/
      - deploy:
          name: Maybe deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              npm run deploy
            fi
